# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c020747557a59ff10c6a06c3a6cd7f839c70eab611bc6c77ca320d463ee409b898cb6a0435bf53e27b516ff788c87fb759cc26f71b1aaa9d6921b7685d296748

test:
  secret_key_base: bfd344522228c09e1c986e8fea948e78a460caa7b3f8126770922ce8aebff56c62045e09c48ec7a21400ae42bd17a7d3b4e91b021dc07d490fd4942be31bdcd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
